TOKEN: "ODA2NTA4MDM2NTc5MzkzNTU2.YBqdJA.ZiyI_aESq1GfNT8j1xCF7np1YEw"
PREFIX: "+"
OWNER_IDS:
  - 584227289592496129
MongoDB: mongodb+srv://cider:cider@cluster0.09t2u.mongodb.net/Cluster0?retryWrites=true&w=majority